COMMON:
  SAVEPATH: ./log
  GPUS: [0]
  SEED: 42

DATA:
  ROOT: ./data
  NAME: flower_photos
  INPUTSIZE: 64
  BATCHSIZE: 32
  NUMWORKER: 32

MODEL:
  BASEMODEL: efficientnet_b0
  NUMCLASSES: 5
  FREEZE: true

TRAIN:
  OPTIMIZER: sgd
  LEARNINGRATE: 0.001
  EPOCHS: 1